components:
  schemas:
    FileUploadMetadataEncrypted:
      description: Encrypted file upload metadata model
      properties:
        payload:
          title: Payload
          type: string
      required:
      - payload
      title: FileUploadMetadataEncrypted
      type: object
    HTTPValidationError:
      properties:
        detail:
          items:
            $ref: '#/components/schemas/ValidationError'
          title: Detail
          type: array
      title: HTTPValidationError
      type: object
    ValidationError:
      properties:
        loc:
          items:
            anyOf:
            - type: string
            - type: integer
          title: Location
          type: array
        msg:
          title: Message
          type: string
        type:
          title: Error Type
          type: string
      required:
      - loc
      - msg
      - type
      title: ValidationError
      type: object
  securitySchemes:
    HTTPBearer:
      scheme: bearer
      type: http
info:
  description: A service to ingest s3 file upload metadata produced by thedata-steward-kit
    upload command
  title: File Ingest Service
  version: 0.1.4
openapi: 3.0.2
paths:
  /health:
    get:
      description: Used to test if this service is alive
      operationId: health_health_get
      responses:
        '200':
          content:
            application/json:
              schema: {}
          description: Successful Response
      summary: health
      tags:
      - FileIngestService
  /ingest:
    post:
      description: Decrypt payload, process metadata, file secret and send success
        event
      operationId: ingestFileUploadMetadata
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/FileUploadMetadataEncrypted'
        required: true
      responses:
        '202':
          content:
            application/json:
              schema: {}
          description: Received and decrypted data successfully.
        '422':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
          description: Validation Error
      security:
      - HTTPBearer: []
      summary: Processes encrypted output data from the S3 upload script and ingests
        it into the Encryption Key Store, Internal File Registry and Download Controller.
      tags:
      - FileIngestService
tags:
- name: FileIngestService
