# Please only mention the non-default settings here:

service_name: fis
token_hashes: [abcdef, ghijkl]
private_key: dummy-key

vault_host: "http://127.0.0.1"
vault_port: 8200
vault_role_id: dummy-role
vault_secret_id: dummy-secret
